const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;
const GRAPHQL_API_BASE_URL = import.meta.env.VITE_GRAPHQL_API_BASE_URL;
const GRAPHQL_API_BEARER_TOKEN = import.meta.env.VITE_GRAPHQL_API_BEARER_TOKEN;

export { API_BASE_URL, GRAPHQL_API_BASE_URL, GRAPHQL_API_BEARER_TOKEN };
